### PR TITLE
Add support for unix_socket_utilization metric.

### PR DESCRIPTION
**Pull request by bjhaid**
This allows litmus to weight a backend's health based on how backed up
the unix socket is.

### CODE REVIEW

**Comment by mrak** [comment]
Maybe a readme entry on how to use?

**Comment by ahayworth** [comment]
+1 to a readme entry.

From the [docs](https://bogomips.org/raindrops/Raindrops/Linux.html) it looks like the method might have performance problems:
```
This method may be significantly slower than its ::tcp_listener_stats counterpart due to the latter being able to use inet_diag via netlink. This parses /proc/net/unix as there is no other (known) way to expose Unix domain socket statistics over netlink.
```

Can we assert that this won't unintentionally slow down litmus_paper too much? The failure case I'm thinking of is "litmus_paper gets bogged down doing TCP stats and fails to respond to health requests" (or some other vital function).

**Comment by bjhaid** [comment]
Readme added.

> Can we assert that this won't unintentionally slow down litmus_paper too much?

Litmus paper already caches metrics and serves stale metrics from the cache so I am not super worried, however find below my lazy man benchmark ran on a production server:

```
irb(main):002:0> a = Time.now; Raindrops::Linux.unix_listener_stats(['/var/run/foo.sock'])['/var/run/foo.sock']; b = Time.now
=> 2018-10-29 13:50:34 +0000
irb(main):003:0> b - a
=> 0.001950495
```

**Comment by ahayworth** [comment]
> This method may be significantly slower
Emphasis on the "may be significantly slower" then. :)

LGTM!

**Comment by lollipopman** [comment]
The algorithm in this pull request: (weight * queued / maxconn), 1), only takes into account queued connections. We typically have zero queued connections on our unicorn application servers, so this algorithm would not provide any balancing feedback information expect in extreme cases where our application servers are overloaded.

Instead we should consider adding a weighting factor for the active connections as well, perhaps something like, max((weight - ((weight * active) / (3 * maxconn) + (2 * weight * queued) / (3 * maxconn))), 1), where we weigh active connections as a 1/3 of the weight and queued connections as 2/3 of the weight. This would provide feedback about which
server is the least loaded:

servers:
  - server-a: maxconn = 30, active = 10, queued = 0
  - server-b: maxconn = 30, active = 30, queued = 0
  - server-c: maxconn = 30, active = 30, queued = 1
  - server-d: maxconn = 30, active = 20, queued = 10

algorithm: max(weight - (weight * queued / maxconn), 1)
  - server-a: weight = 100
  - server-b: weight = 100 
  - server-c: weight = 96.7
  - server-d: weight = 66.7

algorithm: max((weight - ((weight * active) / (3 * maxconn) + (2 * weight * queued) / (3 * maxconn))), 1)
  - server-a: weight = 88.9
  - server-b: weight = 66.7 
  - server-c: weight = 64.4
  - server-d: weight = 55.6

**Comment by bjhaid** [comment]
@lollipopman thanks for your feedback! implemented

**Comment by lollipopman** [comment]
@bjhaid thanks for updating the algorithm, can you also add the algorithm to the readme, as I think that is probably the most interesting part for someone wondering what is being measured by this metric.

**Pull request merged**
