### PR TITLE
Rebuild Docker image as a lighter weight alpine image w/ Ruby 2.6.5

### PR DESCRIPTION
**Pull request by maxfierke**
This rebuilds the Docker image on the latest Ruby 2.6.5 alpine image and runs `litmus_paper` under its own user, rather than `root`.

This image also has the benefit of running under a newer version of Ruby (2.6 vs 2.3), along with a smaller build size (266MB vs 491MB).

If the debian-based aspect of the image is important, I can swap alpine out for one of the `slim-buster` base images instead.

### CODE REVIEW

**Comment by lollipopman** [comment]
thanks @maxfierke this looks really good, we would however prefer a slim buster image, as we run Debian exclusively here at Braintree.

**Comment by ssgelm** [comment]
Additionally we would like to use the system ruby provided by debian.  That may have been your plan but I wanted to make sure that was clear so that you don't inadvertently do extra work. :)

**Comment by maxfierke** [comment]
@ssgelm like `ruby` as-is from the buster debian repos or whatever ruby is built into the `slim-buster` Ruby image? (for context: this is the Dockerfile for the `2.6.5:slim-buster` base image I was thinking of using: https://github.com/docker-library/ruby/blob/82eecb7596c3cb466dd87d4b0350d189a330b925/2.6/buster/slim/Dockerfile)

**Comment by ssgelm** [comment]
@maxfierke To provide some background here: we run litmus_paper under the system version of ruby (e.g. 2.5.1 on buster: https://packages.debian.org/buster/ruby).  Therefore, we would like the Docker image to use the same for consistency.  Is there a particular reason you specifically want ruby 2.6.5, or just because it's the current version?

**Comment by maxfierke** [comment]
Not really. Any sufficiently modern version works for me. I'll switch it to system ruby off the main `buster-slim` image.

**Comment by ssgelm** [comment]
Yeah, the `ruby` package as provided by debian.  Our main desire is to us a package built by debian and not just a tarball that's been `make install`-ed like in the one you linked.

**Pull request merged**
